### ISSUE TITLE
plugin crashing

### ISSUE THREAD

**Issue by karce25** [F5Networks/terraform-provider-f5os#11]
Trying to use F5OS provider to create some  test VLAN and tenant on an rSeries 4600 but the plugin was crashing, after several test, it works

### Terraform Version
Terraform v1.4.5
on windows_386
+ provider registry.terraform.io/f5networks/f5os v1.0.0

### Affected Resource(s)
-Vlan
-Tenant

### Terraform Configuration Files
```hcl

terraform {
  required_providers {
    f5os = {
      source  = "F5Networks/f5os"
      version = "1.0.0"
    }
  }
}

provider "f5os" {
  username = "test"
  password = "xxxx"
  host     = "https://x.x.x.x"
}
resource "f5os_vlan" "vlan-id" {
  vlan_id = 4
  name    = "vlan4"
}

resource "f5os_tenant" "test3" {
  name              = "testtenant"
  image_name        = "BIGIP-15.1.5.1-0.0.14.T4-F5OS.qcow2.zip.bundle"
  mgmt_ip           = "x.x.x.x"
  mgmt_gateway      = "x.x.x.x"
  mgmt_prefix       = 16
  type              = "BIG-IP"
  cpu_cores         = 4
  vlans             = [4]
  running_state     = "deployed"
  virtual_disk_size = 82
}

```
### Error output

Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-f5os_v1.0.0.exe plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 20 [running]:
gitswarm.f5net.com/terraform-providers/terraform-provider-f5os/internal/provider.(*TenantResource).tenantResourceModeltoState(0x1400a630, {0xe473e0, 0x140084f8}, 0x140024a0, 0x13d1a460)
        gitswarm.f5net.com/terraform-providers/terraform-provider-f5os/internal/provider/tenant_resource.go:305 +0x369
00a4a8, ...}, ...)
        gitswarm.f5net.com/terraform-providers/terraform-provider-f5os/internal/provider/tenant_resource.go:241 +0x2b5
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x13d0a270, {0xe473e0, 0x140084f8}, 0x14008540, 0x13f97af0)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_readresource.go:97 +0x5de
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x13d0a270, {0xe473e0, 0x14008498}, 0x14018620)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/proto6server/server_readresource.go:52 +0x463
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xd0cf40, 0x13c01040}, {0xe473e0, 0x140081e0}, 0x14014280, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:383 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x13d24b40, {0xe49428, 0x13dd6000}, 0x140241e0, 0x13d1f890, 0x1279f68, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xed7
google.golang.org/grpc.(*Server).handleStream(0x13d24b40, {0xe49428, 0x13dd6000}, 0x140241e0, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x25f

Error: The terraform-provider-f5os_v1.0.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by RavinderReddyF5** [comment]
Hi @karce25 please verify on latest version and report for any new issues
